### ISSUE TITLE
Ethereum whale watch details

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#253]
Whale watch events return top 10 whales in each category. We only display top whales on the card. Clicking on card details should show users about all the whales for that event.

If you want to get information about the addresses, you can use the `/address_info/ethereum` endpoint.

**Comment by peersky** [comment]
@zomglings I would like to implement this with dedicated screen,`board` and whale icon on sidebar. 

In order to do that, can we first optimize API? I would like to have such functionality:

- [ ] Remove ability to create whale subscription from subscription screen as well as from /stream endpoint
- [ ] Add `GET /whale/types endpoint that would return [SubscriptionTypesListResponse](https://github.com/bugout-dev/moonstream/blob/e47a0c8760635877bc73c0522940cdca6b4bbabb/backend/moonstream/data.py#L24) containing only legit subscription types for whales
- [ ] Add `GET /whales` endpoint that could have following query params: `source`: [SubscriptionResourceData](https://github.com/bugout-dev/moonstream/blob/e47a0c8760635877bc73c0522940cdca6b4bbabb/backend/moonstream/data.py#L2), `start_time`, `end_time`
- [ ] Improve `GET /whales` endpoint with some extra keys such as `metrics: ["nbrTX", "nbrRX", "valueIn", "valueOut", "totalValue"]` (and create data type for that?); `AddressCohort` - this would be useful if we can define cohorts of addresses (let's say LOOT NFTs, Uniswap contracts, Binance address) etc.

**Comment by zomglings** [comment]
After discussion at engineering sync, we made the following decisions:

### Subscriptions and API endpoint

We will not remove whale watch subscriptions from frontend. Users could still want this information in their streams to consume it through the API. Instead, we will follow the same pattern as we implemented for the `/nfts` endpoint.

Rename [`NFTProvider`](https://github.com/bugout-dev/moonstream/blob/e47a0c8760635877bc73c0522940cdca6b4bbabb/backend/moonstream/providers/bugout.py#L330) to `PublicDataProvider`.

Define a new `whalewatch_public_provider` that gets whalewatch data from `PublicDataProvider` instead of `BugoutProvider`. Use that to serve the `/whales` endpoint.

`/whales/` endpoint to be implemented similarly to `/nfts/`.

### Whale types

Let's not worry about this now, we only support Ethereum. If we do want to at least make a nod to this, we can put our Ethereum whale watch data at `/whales/ethereum`.

First new whale can be txpool whale - who is submitting a lot of transactions? Not a priority at the moment.

### Extra keys on GET /whales

Since we have so few keys, just handle on client side for now.

**Comment by zomglings** [comment]
Stale.
